# Site settings
title: MaRy's Blog
#email: margase1988@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
#github_username:  jekyll

highlighter: pygments
# Build settings
markdown: redcarpet
